Cleanup orphan GCP private links
mongodb/mongodb-atlas-kubernetes pull request #1401
Opened 2024-02-26 14:35 UTC by josvazg

### All Submissions:

* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?

2024-02-26 14:46 UTC, josvazg commented
![Screenshot 2024-02-26 at 15 46 36](https://github.com/mongodb/mongodb-atlas-kubernetes/assets/514554/55be5fd5-a6bf-4b89-ab15-a2ac5c7f5529)

2024-02-26 20:36 UTC, helderjs commented
@josvazg Do you know why these GCP resources are becoming orphans?

2024-02-26 20:37 UTC, helderjs approved these changes
LGTM

2024-02-26 20:48 UTC, josvazg commented
> @josvazg Do you know why these GCP resources are becoming orphans?

Not really. I thought we could create a follow up for that. But here I wanted to have a fix that would eliminate the recurrent issue for now.

I suspect they become orphan on some tests failures that do not clean up properly after themselves. I do not believe it happens all the time, it is going to be tricky to debug.

I will create and link the follow up here.

2024-02-27 09:10 UTC, josvazg commented
Follow up to investigate how the e2e cleanup might fails and turn those resources into orphans CLOUDP-234041

2024-02-27 10:03 UTC, s-urbaniak commented on tools/clean/provider/gcp.go
> +			return err
wrap using `fmt.Errorf("error while iterating addresses in project %v region $v: %w", gcp.projectID, region, err)

2024-02-27 10:04 UTC, s-urbaniak commented on tools/clean/provider/gcp.go
> +			return err
`return fmt.Errorf("error parsing creation timestamp %q: %w", addr.GetCreationTimestamp(), err)`

2024-02-27 10:04 UTC, s-urbaniak commented on tools/clean/provider/gcp.go
> +			return err
this is actually fine not wrapping, as the error is generated here, only once, and is specific :-)

2024-02-27 10:06 UTC, s-urbaniak commented on tools/clean/provider/gcp.go
> +				return err
`return fmt.Errorf("error deleting forwarding rule %q in region %q: %w", region, frName, err)`

2024-02-27 10:06 UTC, s-urbaniak commented on tools/clean/provider/gcp.go
> +			return err
`return fmt.Errorf("error deleting IP address %q in region %q: %w", addr.GetName(), frName, err)`

2024-02-27 10:06 UTC, s-urbaniak requested changes
just a few error handling nits, else lgtm

2024-02-27 13:12 UTC, josvazg commented on Makefile
> +	echo "licenses.csv needs to be recalculated: git rebase AND run 'make licenses.csv'"; exit 1; \
This tripped me for quite a while.

The check will fail if you need to rebase as well, even thought locally the `licenses.csv` seems up to date, if the diff includes a rebase, the go.mod will be different and thus the `licenses.csv` need to be recomputed.

While I was trying to fix this I also removed our dependency on shasum and use git SHAs directly instead.

2024-02-27 13:22 UTC, helderjs approved these changes

2024-02-27 13:26 UTC, s-urbaniak approved these changes
lgtm

2024-02-27 13:35 UTC, merged