do not execute by steps as callbacks
mongodb/mongodb-atlas-kubernetes pull request #1420
Opened 2024-03-04 17:01 UTC by s-urbaniak

### All Submissions:

* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.

During e2e the execution of `By` steps was observed to run concurrently:
```
2024-03-04T16:18:06.6182325Z   STEP: Update team role in the project @ 03/04/24 16:07:45.99
2024-03-04T16:18:06.6184071Z   STEP: Remove all teams from the project @ 03/04/24 16:07:45.998
```

This fixes it

2024-03-04 17:06 UTC, s-urbaniak commented
As per https://onsi.github.io/ginkgo/#documenting-complex-specs-by:
> By takes an optional function of type `func()`. When passed such a function `By` will **immediately** call the function. This allows you to organize your Its into groups of steps.

2024-03-04 17:21 UTC, josvazg approved these changes

2024-03-11 08:35 UTC, josvazg commented
Should we reap this one? seems it was a red herring.

2024-03-11 08:36 UTC, josvazg requested changes
It was a red herring, this does not fix the issue.

2024-03-11 09:14 UTC, closed without merging