release instruction and script improvements
mongodb/mongodb-atlas-kubernetes pull request #1465
Opened 2024-03-21 11:42 UTC by s-urbaniak

### All Submissions:

* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.

2024-03-21 11:43 UTC, s-urbaniak commented on scripts/release-redhat-certified.sh
> +
Note: https://github.com/redhat-openshift-ecosystem/certified-operators/pull/3619 was done using this script.

2024-03-21 13:02 UTC, josvazg reviewed
These manual changes are still needed?

Eg:

> Before posting the PR there is a manual change you need to make:
>
> * Ensure to add the `quay.io/` prefix in all Operator image references.
> You can see an [example fixed PR here on Community Operators for version 1.9.1](https://github.com/k8s-operatorhub/community-operators/pull/3457).

I mean it has been fixed for **certified**, we could as well do it for the other 2.

2024-03-21 13:04 UTC, josvazg approved these changes
LGTM, I just wonder if we should also fix the other 2 redhat releases not to need to setup the `quay.io/` prefix manually.

2024-03-21 13:43 UTC, helderjs approved these changes

2024-03-25 10:55 UTC, helderjs requested changes

2024-03-25 10:55 UTC, helderjs commented on scripts/release-redhat.sh
Should it be done also in release-redhat-openshift.sh?

2024-03-25 11:03 UTC, s-urbaniak commented on scripts/release-redhat.sh
@helderjs no, `release-redhat-openshift.sh` just copies over stuff that is already touched by `release-redhat.sh`

2024-03-25 11:08 UTC, helderjs approved these changes

2024-03-25 12:50 UTC, merged