CLOUDP-239117: Increased resources limits for AKO container
mongodb/mongodb-atlas-kubernetes pull request #1472
Opened 2024-03-25 12:15 UTC by igor-karpukhin

### All Submissions:

* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.

2024-03-25 14:28 UTC, s-urbaniak requested changes

2024-03-25 14:28 UTC, s-urbaniak commented on config/manager/manager.yaml
> +              cpu: 1000m
we shouldn't set cpu limits.

2024-03-25 14:29 UTC, s-urbaniak commented on config/manager/manager.yaml
> +              cpu: 1000m
xref https://home.robusta.dev/blog/stop-using-cpu-limits

2024-03-25 14:39 UTC, s-urbaniak commented
generally: I'd recommend running integration tests locally, using kind with a deployed Prometheus setup and use https://github.com/robusta-dev/krr to measure.

I can help here if needed.

2024-03-25 17:39 UTC, igor-karpukhin commented
As per our conversation @s-urbaniak I updated the PR.

2024-03-26 10:26 UTC, s-urbaniak approved these changes

2024-03-26 10:44 UTC, merged