CLOUDP-249584: Fix search nodes when running on Gov
mongodb/mongodb-atlas-kubernetes pull request #1596
Opened 2024-05-17 16:32 UTC by helderjs

### All Submissions:

* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes-template.md if your changes should be included in the release notes for the next release.

2024-05-20 07:34 UTC, josvazg approved these changes

2024-05-21 06:20 UTC, s-urbaniak requested changes

2024-05-21 06:20 UTC, s-urbaniak commented on pkg/controller/atlas/provider.go
> +		hasSearchNodes := atlasResource.Spec.DeploymentSpec != nil && len(atlasResource.Spec.DeploymentSpec.SearchNodes) >= 0
```suggestion
		hasSearchNodes := atlasResource.Spec.DeploymentSpec != nil && len(atlasResource.Spec.DeploymentSpec.SearchNodes) > 0
```

if `len(atlasResource.Spec.DeploymentSpec.SearchNodes) == 0`, then no search nodes are defined.

2024-05-22 08:52 UTC, josvazg approved these changes

2024-05-22 10:14 UTC, s-urbaniak approved these changes

2024-05-22 10:14 UTC, merged