CLOUDP-269300: Bump to Go 1.23
mongodb/mongodb-atlas-kubernetes pull request #1841
Opened 2024-09-27 10:27 UTC by roothorp

Including the relevant golangci version bump to support Go 1.23.
Also includes other miscellaneous version updates for devbox (these will be automated similar to dependabot in future).

wrt `exportloopref`:
> Since Go1.22 (loopvar) this linter is no longer relevant. Replaced by copyloopvar.

### All Submissions:

* [ ] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes-template.md if your changes should be included in the release notes for the next release.

2024-09-30 07:53 UTC, josvazg commented
@roothorp I would make this a draft until we figure out the licenses issue. BTW, I can take this PR if you want.

2024-09-30 09:32 UTC, josvazg commented
Taking this from @roothorp will make it a draft while I figure out the licenses issue

2024-09-30 17:52 UTC, josvazg commented on Makefile
> +	go run github.com/google/$(GO_LICENSES)@v$(GO_LICENSES_VERSION) csv --include_tests $(BASE_GO_PACKAGE)/... > licenses.csv
Not the prettiest fix, but the only one I could find. 

From here:
https://github.com/google/go-licenses/issues/149#issuecomment-2208882223

Seems we won't be able to use devbox/nix for the go-licenses binary and instead need to use it as a module dep. 

cc @roothorp

2024-09-30 17:58 UTC, josvazg approved these changes

2024-10-01 12:16 UTC, s-urbaniak commented on pkg/controller/atlasproject/custom_roles.go
> +				err = errors.Join(err, fmt.Errorf("%s", stat.Error))
```suggestion
				err = errors.Join(err, fmt.Errorf("%w", stat.Error))
```

2024-10-01 12:17 UTC, s-urbaniak commented on pkg/controller/atlasproject/custom_roles.go
> +				err = errors.Join(err, fmt.Errorf("%s", stat.Error))
```suggestion
				err = errors.Join(err, fmt.Errorf("%w", stat.Error))
```

2024-10-01 12:17 UTC, s-urbaniak requested changes
one nit, else lgtm 👍

2024-10-01 13:00 UTC, josvazg commented on pkg/controller/atlasproject/custom_roles.go
> +				err = errors.Join(err, fmt.Errorf("%w", stat.Error))
```suggestion
				err = errors.Join(err, fmt.Errorf("%s", stat.Error))
```

2024-10-01 13:01 UTC, josvazg commented on pkg/controller/atlasproject/custom_roles.go
> +				err = errors.Join(err, fmt.Errorf("%w", stat.Error))
stat.Error is a `string`

```suggestion
				err = errors.Join(err, fmt.Errorf("%s", stat.Error))
```

2024-10-01 13:01 UTC, josvazg commented on pkg/controller/atlasproject/custom_roles.go
> +				err = errors.Join(err, fmt.Errorf("%w", stat.Error))
stat.Error is a `string`

```suggestion
				err = errors.Join(err, fmt.Errorf("%s", stat.Error))
```

2024-10-01 16:03 UTC, s-urbaniak approved these changes

2024-10-01 16:07 UTC, helderjs approved these changes

2024-10-01 16:15 UTC, merged