CLOUDP-277876: Reap orphan connection secrets
mongodb/mongodb-atlas-kubernetes pull request #1856
Opened 2024-10-10 10:35 UTC by josvazg

### All Submissions:

* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?

2024-10-10 11:01 UTC, helderjs requested changes

2024-10-10 11:01 UTC, helderjs commented on pkg/controller/atlasdatabaseuser/databaseuser.go
> +		r.Log.Info("Removed %d orphan secrets on project %s bound to an non existent deployment:")
I'd log this as debug to avoid pollute logs with less relevant info.

2024-10-10 19:52 UTC, helderjs approved these changes

2024-10-11 13:59 UTC, s-urbaniak commented on pkg/controller/connectionsecret/connectionsecrets.go
> +		if err := k8sClient.Delete(ctx, &secret); err != nil {
the method `ReapOrphanConnectionSecrets` is doing more than the reader is assuming. it is also causing the side-effect of deleting secrets. Either we:
1. factor deletion in its own function, not called in a `Read...` function
2. Rename this function to something that informs the reader that a deletion happens here as well

2024-10-11 14:00 UTC, s-urbaniak approved these changes

2024-10-11 14:02 UTC, merged