CLOUDP-86187: cluster update (replicationSpecs)
mongodb/mongodb-atlas-kubernetes pull request #188
Opened 2021-03-29 16:44 UTC by antonlisovenko

WIP

2021-03-30 13:06 UTC, vasilevp requested changes

2021-03-30 13:35 UTC, antonlisovenko commented on pkg/controller/atlascluster/cluster.go
> -	if err = compat.JSONSliceMerge(&result.ReplicationSpecs, atlasCluster.ReplicationSpecs); err != nil {
my understanding is that by this time the `result` is a full copy of the cluster from Atlas? So will have all IDs etc there. We only need to apply our changes to `ReplicationSpecs`  on top of what Atlas provides? I could be missing something there - please correct me if I'm wrong

2021-03-30 15:16 UTC, vasilevp commented on pkg/controller/atlascluster/cluster.go
> -	if err = compat.JSONSliceMerge(&result.ReplicationSpecs, atlasCluster.ReplicationSpecs); err != nil {
Copying `spec` will overwrite `ReplicationSpecs` if it's not empty, thus erasing those IDs

2021-03-31 10:28 UTC, vasilevp approved these changes

2021-03-31 10:37 UTC, merged