CLOUDP-280230: Network peering controller and CRD
mongodb/mongodb-atlas-kubernetes pull request #1930
Opened 2024-11-14 17:04 UTC by josvazg

Network peering support is sliced into 3 logical changes:

1. Fixing to the already merged translation layer.
2. Adding the CRD types and manifest files.
3. Adding the controller code and tests.
4.  🚧 **(WIP) Unit tests**

### All Submissions:

* [X] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?

2024-12-02 14:08 UTC, josvazg commented on config/crd/bases/atlas.mongodb.com_atlasprivateendpoints.yaml
> -                  to
cc @helderjs have you find this typo in your change? The description name should match the actual field name

2024-12-19 16:04 UTC, josvazg commented
Helm test fail because the CRDs in the helm package still do not include network peering.

2025-01-23 08:58 UTC, s-urbaniak commented on api/v1/atlasnetworkpeering_types_test.go
> +	launchProjectRefCELTests(
q: what is being asserted here? `launchProjectRefCELTests` has no indication what test cases are being executed.

2025-01-23 09:00 UTC, s-urbaniak commented on api/v1/atlasnetworkpeering_types.go
> +	Spec   AtlasNetworkPeeringSpec          `json:"spec,omitempty"`
q: are we following the rules described in https://ahmet.im/blog/crd-generation-pitfalls/index.html#explicit-required-or-optional-on-every-field for all spec fields?

2025-01-23 09:02 UTC, s-urbaniak commented on internal/operator/builder.go
> +	npeReconciler := atlasnetworkpeering.NewAtlasNetworkPeeringsReconciler(
blocking: this needs to be in the controller registry https://github.com/mongodb/mongodb-atlas-kubernetes/blob/main/internal/controller/registry.go

2025-01-23 09:09 UTC, s-urbaniak commented on internal/controller/atlasnetworkpeering/atlasnetworkpeering_controller.go
> +	deleted := req.networkPeering.DeletionTimestamp != nil
blocking: this doesn't catch the case of deletion timestamp being zero. Please use the `IsZero()` method which asserts both nil and zero time.

2025-01-23 09:20 UTC, s-urbaniak commented on internal/indexer/indexer.go
> +func RegisterAll(ctx context.Context, mgr manager.Manager, logger *zap.Logger) error {
blocking: undo this change, we need to retain `c cluster.Cluster` as a parameter.

2025-01-23 09:22 UTC, s-urbaniak commented on internal/controller/atlasnetworkpeering/atlasnetworkpeering_controller.go
> +func (r *AtlasNetworkPeeringReconciler) sync(req *reconcileRequest, atlasPeer *networkpeering.NetworkPeer) ctrl.Result {
blocking: what is being `sync`'ed here? as I read the code, updates in the spec are silently ignored. If the spec is immutable, we should talk w/ PM whether it makes sense to make the whole spec immutable (guarded via CEL) if Atlas doesn't support updates to network peers.

2025-01-23 09:29 UTC, s-urbaniak requested changes
a couple of comments, great work! 👏

2025-01-23 10:02 UTC, s-urbaniak commented on internal/controller/atlasnetworkpeering/atlasnetworkpeering_controller.go
> +func (r *AtlasNetworkPeeringReconciler) sync(req *reconcileRequest, atlasPeer *networkpeering.NetworkPeer) ctrl.Result {
I see we have updates in Atlas for both connections https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Network-Peering/operation/updatePeeringConnection and containers https://www.mongodb.com/docs/atlas/reference/api-resources-spec/v2/#tag/Network-Peering/operation/updatePeeringContainer.

Why aren't we leveraging that?

2025-01-23 13:16 UTC, josvazg commented
Making this a draft again, as we plan to re-design the Peering Connection - Network Container relatinship, to make Networks a first class CRD as well.

Still I would like to address most of the comments as I will be using this branch for continuing work and this and will need it to be rebase-able as close to main as possible.

2025-01-23 13:52 UTC, josvazg commented on api/v1/atlasnetworkpeering_types.go
> +	Spec   AtlasNetworkPeeringSpec          `json:"spec,omitempty"`
I will double check that for when we surface this again, both for the NetworkContainer and the PeeringConnection CRDs.

2025-01-23 13:56 UTC, josvazg commented on api/v1/atlasnetworkpeering_types_test.go
> +	launchProjectRefCELTests(
This is interesting, because all cases were always the same for all the users. The thing is, the only change was the dual reference was used by one or another underlying CRD type, but that does not change the behaviour or correctness of how the dual ref is handled.


We could fix this in a separate PR, I think we can have a single test for this in a single place and just keep on adding underlaying CRDs to test as carriers of the dual reference to be tested.
WDYT?

2025-01-23 13:56 UTC, josvazg commented on internal/controller/workflow/reason.go
> +	NetworkPeeringConnectionResetting ConditionReason = "NetworkPeeringConnectionResetting"
will remove

2025-01-23 13:57 UTC, josvazg commented on internal/indexer/indexer.go
> +func RegisterAll(ctx context.Context, mgr manager.Manager, logger *zap.Logger) error {
Right! I missed this detail on the rebase, I will fix

2025-01-23 13:58 UTC, josvazg commented on internal/operator/builder.go
> +	npeReconciler := atlasnetworkpeering.NewAtlasNetworkPeeringsReconciler(
Right! yep I also need to fix this for comply with the new **Cluster** support

2025-01-23 17:14 UTC, josvazg commented on internal/controller/workflow/reason.go
> +	NetworkPeeringConnectionResetting ConditionReason = "NetworkPeeringConnectionResetting"
done in next update

2025-02-06 18:07 UTC, josvazg commented
This has been split into 2 sequential PRs: #2101 & #2103
Once I am sure all the relevant bits have been moved to those, I shall close this PR.

2025-02-18 21:02 UTC, josvazg commented
No longer required, replaced by #2100 & #2103

2025-02-18 21:02 UTC, closed without merging