Pass git version to the binary on build
mongodb/mongodb-atlas-kubernetes pull request #195
Opened 2021-04-01 15:12 UTC by vasilevp

2021-04-01 15:15 UTC, vasilevp commented on .github/workflows/release-post-merge.yml
> +          build_args: VERSION=${{ steps.tag.outputs.tag }}
This is the only change here, everything else is formatting

2021-04-01 15:15 UTC, vasilevp commented on .github/workflows/test.yml
> +          fetch-depth: 0 # required for tags
Same here

2021-04-01 15:44 UTC, leo-ri commented on .github/workflows/test.yml
> +          fetch-depth: 0 # required for tags
hmmm....we don't get git tags, no?

2021-04-01 15:54 UTC, leo-ri approved these changes

2021-04-09 17:05 UTC, antonlisovenko requested changes
Looks good 👍 
please add a simple unit test to ensure the correct user agent is sent.

2021-04-09 17:05 UTC, antonlisovenko commented on main.go
> +	if config.Version {
I'd suggest to always print the version on the Operator start.

2021-04-09 17:05 UTC, antonlisovenko commented on main.go
> +	flag.BoolVar(&config.Version, "version", false, "Display current version and exit")
not sure I understand the value of this flag. Can we just always print the version on the Operator start?

2021-04-09 17:05 UTC, antonlisovenko commented on pkg/controller/atlas/client.go
> +	client.UserAgent = fmt.Sprintf("%s/%s (%s;%s)", "MongoDBAtlasKubernetesOperator", ProductVersion, runtime.GOOS, runtime.GOARCH)
can we please add the unit test for this?

2021-04-23 10:22 UTC, antonlisovenko approved these changes
LGTM!

2021-04-23 11:21 UTC, merged