Update go to 16 and bump dependencies
mongodb/mongodb-atlas-kubernetes pull request #339
Opened 2021-11-11 09:51 UTC by fabritsius

2021-11-11 10:02 UTC, leo-ri requested changes

2021-11-11 10:06 UTC, fabritsius commented on Dockerfile
> -    microdnf remove yum &&\
It seems `yum` became protected in `go1.16` image:
```
Problem: The operation would result in removing the following protected packages: yum
```
It doesn't allow to remove `yum` maybe there is an alternative walk-around.

2021-11-11 10:09 UTC, fabritsius commented on .github/actions/gen-install-scripts/Dockerfile
> +RUN GO111MODULE=on go get github.com/mikefarah/yq/v4
Not sure. We should if all other installations also use modules. I haven't tried, this is just a safer initial change.

2021-11-11 10:10 UTC, fabritsius commented on .github/actions/gen-install-scripts/Dockerfile
> +RUN GO111MODULE=on go get github.com/mikefarah/yq/v4
No harm in trying. Thanks you)

2021-11-12 09:52 UTC, fabritsius commented on .github/actions/gen-install-scripts/Dockerfile
> +RUN GO111MODULE=on go get github.com/mikefarah/yq/v4
Works 👍🏻

2021-11-12 12:28 UTC, leo-ri approved these changes

2021-11-12 12:28 UTC, merged