CLOUDP-159055: Support copySettings field for BackupSchedule
mongodb/mongodb-atlas-kubernetes pull request #870
Opened 2023-02-10 18:59 UTC by helderjs

### All Submissions:

* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.

2023-02-13 14:48 UTC, igor-karpukhin requested changes
Looks good in general, please update integration test as well (deployment_test.go)

2023-02-13 14:48 UTC, igor-karpukhin commented on pkg/controller/validate/validate.go
> +func BackSchedule(bSchedule *mdbv1.AtlasBackupSchedule, deployment *mdbv1.AtlasDeployment) error {
```suggestion
func BackupSchedule(bSchedule *mdbv1.AtlasBackupSchedule, deployment *mdbv1.AtlasDeployment) error {
```

2023-02-13 14:48 UTC, igor-karpukhin commented on pkg/controller/atlasdeployment/backup.go
> +	if err = validate.BackSchedule(bSchedule, deployment); err != nil {
```suggestion
	if err = validate.BackupSchedule(bSchedule, deployment); err != nil {
```

2023-02-14 18:39 UTC, igor-karpukhin approved these changes
Looks good 👍

2023-02-22 10:34 UTC, fabritsius approved these changes
Looks Great 👍

2023-02-22 15:50 UTC, merged