CLOUDP-165710: Fixed AtlasProject reconcile loop
mongodb/mongodb-atlas-kubernetes pull request #894
Opened 2023-03-13 15:51 UTC by igor-karpukhin

### All Submissions:

Fixed AtlasProject reconcile loop so it won't prevent processing of other features if one feature is not configured correctly.

* [x] Have you signed our [CLA](https://www.mongodb.com/legal/contributor-agreement)?
* [ ] Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes (if there is one).
* [ ] Update docs/release-notes/release-notes.md if your changes should be included in the release notes for the next release.

2023-03-13 17:01 UTC, helderjs requested changes

2023-03-13 19:34 UTC, igor-karpukhin commented on pkg/controller/atlasproject/atlasproject_controller.go
> +	if result = ensureIPAccessList(ctx, projectID, project); result.IsOk() {
Good catch! Removed this leftover.

2023-03-15 09:36 UTC, helderjs approved these changes

2023-03-16 09:48 UTC, fabritsius approved these changes
Looks Great 👍 

It's ok to remove `logIfWarning()` from `isOk()` sections and can be merged afterwards

2023-03-19 12:07 UTC, igor-karpukhin commented on pkg/controller/atlasproject/atlasproject_controller.go
> +	for i := range results {
@helderjs I'd say this is a good idea. Let's add it to the list of improvements doc.

2023-03-31 16:11 UTC, merged